name: Pytest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./tests/requirements_tests.txt

    - name: Docker Build
      run: docker compose up -d --build
    - name: Docker Run
      run: docker compose up -d
    - name: Run tests
      run: python -m pytest --import-mode=append tests/
