name: Pytest

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./tests/requirements_tests.txt

    - name: Docker Build and Push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t atf-backend-test:v1 .
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag atf-backend-test:v1 $DOCKER_USERNAME/atf-backend-test:v1
        docker push $DOCKER_USERNAME/atf-backend-test:v1

    - name: Start Kind Cluster
      run : |
        kind create cluster --name aboutthefit-test --config=./tests/workerNodes.yaml

    - name: Apply Kubernetes Manifests
      run: kubectl apply -f ./tests/deployment-test/

    - name: Run tests
      run: python -m pytest --import-mode=append tests/
